Vector,Matrix And Tensor

In [1]:
import numpy as np

In [2]:
vector = np.array([5,8,6])
print("Vector: ",vector)

matrix =np.array([[1,2,0],
                  [7,0,1]])
print("Matrix:\n",matrix)

tensor = np.array([[[1,2],
                    [4,5]],
                   [[1,8],
                    [7,6]]])
print("Tensor:\n",tensor)

Vector:  [5 8 6]
Matrix:
 [[1 2 0]
 [7 0 1]]
Tensor:
 [[[1 2]
  [4 5]]

 [[1 8]
  [7 6]]]
