CREATING ARRAY FROM SCRATCH / METHODS

In [2]:
import numpy as np

🔹zeros gives null matrix, Size is
 terminated 
   within tuple (row,column).
   e.g - (3,4)

In [22]:
zeros = np.zeros((3,4))
print("Zeros array: \n",zeros)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


🔹ones gives unit matrix, Size is
 terminated 
   within tuple (row,column).
   e.g - (2,3)

In [23]:
one = np.ones((2,3))
print("unit matrix:\n",one)

unit matrix:
 [[1. 1. 1.]
 [1. 1. 1.]]


🔹full gives full same element's matrix, Size is
 terminated 
   within tuple ((row,column),element ).
   e.g - ((3,3),5)

In [24]:
full = np.full((3,3), 5) 
print("full array:\n",full)

full array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


🔹random : for random values matrix. (row,colum)

🔹Values are fluetuate within 0 - 1

In [26]:
random = np.random.random((2,2))
print("Random matrix:\n",random)

Random matrix:
 [[0.73665932 0.3252604 ]
 [0.13310286 0.68976979]]


🔹sequence : arange(start,end,stepSize) AND it gives a sequence array.

In [3]:
seq = np.arange(0,11)
print("Sequence array:",seq)

# OR
seq1 = np.arange(0,11,2)
print("Seq1 array:",seq1)

Sequence array: [ 0  1  2  3  4  5  6  7  8  9 10]
Seq1 array: [ 0  2  4  6  8 10]
