In [4]:
import numpy as np

### 🔹 Array Creation:

1. An array must be taking a list in python.
2. Within a parameters.([[]])

In [ ]:
arr1d = np.array([1,8,3])
print("1D array:\n",arr1d)

arr2d = np.array([[1,4,6],
                  [4,9,0]])
print("2D array:\n",arr2d)


1D array:
 [1 8 3]
2D array:
 [[1 4 6]
 [4 9 0]]


array([1, 8, 3])