### 🔹 VECTOR OPERATION 

In [1]:
import numpy as np

In [2]:
vector1 = np.array([2,5,6,7,8])
vector2 = np.array([7,9,3,1,7])

print("Vector addition : ",vector1 + vector2)
print("Vector multiplication : ",vector1 * vector2)
print("Dot product : ", np.dot(vector1 , vector2))

angle = np.arccos(np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2)))

print("Angle (radians):", angle)
print(f"Angle (degrees): {round(np.degrees(angle), 3)}°")

Vector addition :  [ 9 14  9  8 15]
Vector multiplication :  [14 45 18  7 56]
Dot product :  140
Angle (radians): 0.7024126186104547
Angle (degrees): 40.245°


In [ ]:
#VECTORIZING: 

res_typ = np.array(["Pasta Wine","Libya","EX Ero","Biriyani","Royal Mint"])
vectorized = np.vectorize(str.upper)
print("Vectorized value: ",vectorized(res_typ))

Vectorized value:  ['PASTA WINE' 'LIBYA' 'EX ERO' 'BIRIYANI' 'ROYAL MINT']


#### BroadCasting :

In [13]:
sales_data = np.array([
    [1, 150000 , 180000, 220000, 250000 ], # Desi Biriyani
    [2, 120000, 140000, 160000, 190000],     # Foreign res
    [3, 200000, 230000, 260000, 300000],     # Pizza Store
    [4, 180000, 210000, 240000, 270000],     # Burger point
    [5, 160000,185000 ,205000, 230000]     # Dolly Chai
])

montly_avg = sales_data[: ,1:] / 12   # here 12 divides on each individual element.
print("Montly_avg:\n",montly_avg,3)

Montly_avg:
 [[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]] 3
