ARRAY'S PROPERTIES :

In [1]:
import numpy as np

🔹SYNTAX : array_name.properties   (shape,ndim,size,dtype etc)

In [2]:
arr1 = np.array([[4,8,3],
                [7,0,4]])


## properties:

print("Shape: ",arr1.shape)
print("Dimension: ",arr1.ndim)
print("Size: ",arr1.size)
print("Data Type: ",arr1.dtype)


Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64


🔹Array Reshaping 

In [3]:
# NORMAL ARRAY : 
arr2 = np.arange(12)   # arange(parameter) # arange(start,end)
print("Original array: ",arr2)

# RESHAPING :
reshaped = arr2.reshape((3,4)) # reshape((row,column))
print("Reshaped array : \n",reshaped)

# Flatting i.e. In a Single Row :
flat = reshaped.flatten()
print("\n Flattened array: ",flat)

# Ravele : (returns view , instead of copy)
ravele = flat.ravel()
print("\n reveled array:",ravele)

# Transpose :
transpose = reshaped.T
print("Transpose: \n",transpose)


Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
